model_list:
  - model_name: claude-sonnet-4.5
    litellm_params:
      model: openai/bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0
      api_base: https://chat.aicopilot.aws.mskcc.org/api/v1
      api_key: os.environ/WEBUI_SESSION_TOKEN
      max_tokens: 65536
    model_info:
      verify_ssl: false
  
  - model_name: claude-sonnet-4
    litellm_params:
      model: openai/bedrock/us.anthropic.claude-sonnet-4-20250514-v1:0
      api_base: https://chat.aicopilot.aws.mskcc.org/api/v1
      api_key: os.environ/WEBUI_SESSION_TOKEN
      max_tokens: 65536
    model_info:
      verify_ssl: false
  
  - model_name: claude-3.7-sonnet
    litellm_params:
      model: openai/bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0
      api_base: https://chat.aicopilot.aws.mskcc.org/api/v1
      api_key: os.environ/WEBUI_SESSION_TOKEN
      max_tokens: 65536
    model_info:
      verify_ssl: false
  
  - model_name: claude-3.5-sonnet
    litellm_params:
      model: openai/bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0
      api_base: https://chat.aicopilot.aws.mskcc.org/api/v1
      api_key: os.environ/WEBUI_SESSION_TOKEN
      max_tokens: 8192
    model_info:
      verify_ssl: false
  
  - model_name: claude-haiku-4-5-20251001
    litellm_params:
      model: openai/bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0
      api_base: https://chat.aicopilot.aws.mskcc.org/api/v1
      api_key: os.environ/WEBUI_SESSION_TOKEN
      max_tokens: 65536
    model_info:
      verify_ssl: false
  
  - model_name: claude-3.5-haiku
    litellm_params:
      model: openai/bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0
      api_base: https://chat.aicopilot.aws.mskcc.org/api/v1
      api_key: os.environ/WEBUI_SESSION_TOKEN
      max_tokens: 65536
    model_info:
      verify_ssl: false

litellm_settings:
  drop_params: true
  telemetry: false
  ssl_verify: false

general_settings:
  master_key: sk-1234
